### ISSUE TITLE
Keyboard Toolbar Doesn't Show

### ISSUE THREAD

**Issue by Mcrich23** [danielsaidi/RichTextKit#157]
When using the `.toolbar` modifier in regards to the keyboard for the RichTextEditor, the keyboard toolbar does not appear.

**Comment by danielsaidi** [comment]
Hi @Mcrich23 

Yes, this is a known limitation when using a SwiftUI `ViewRepresentable`, which the `RichTextEditor` is.

The `RichTextEditor` docs mention this:


Since the view wraps a native `UIKit` or `AppKit` text view, you can't apply `.toolbar` modifiers to it, like you can do with other SwiftUI views. This means that this doesn't work:

 ```swift
 RichTextEditor(text: $text, context: context)
     .toolbar {
         ToolbarItemGroup(placement: .keyboard) {
             ....
         }
     }
 ```

This will not show anything. To work around this limitation, use a ``RichTextKeyboardToolbar`` instead.

**Comment by danielsaidi** [comment]
@Mcrich23 You can have a look at the demo app for an example on how to use that toolbar.
