### ISSUE TITLE
Toolbar 

### ISSUE THREAD

**Issue by Maverick1000** [danielsaidi/RichTextKit#37]
How to add RichTextKeyboardToolbar when using in a UIKit project.

**Comment by danielsaidi** [comment]
Hi! This is primarily a SwiftUI library, so the only UIKit part in it is the RichTextView.

**Comment by Maverick1000** [comment]
Under UKit dose your tool allow text to be formated with rich text  or just view a string in rich text format?

**Comment by danielsaidi** [comment]
It’s an editor, the SwiftUI editor uses it on iOS.

**Comment by Maverick1000** [comment]
So it editor only under SwiftUI? if yes, when under UIKit is it still an editor without a toolbar?  if yes,  do have to create my own toolbar with options like "[.undo, .redo, .copy]".  Under UIKit is it possible to add RichTextColorPicker as action?

**Comment by danielsaidi** [comment]
Everything the SwiftUI editor does with the rich text, it does with true underlying UIKit and AppKit views. You can have a look at how SwiftUI sets colors and just call the same functions in the UIKit editor.

I suggest reading through the documentation and the demo app to see how it all connects.

**Comment by Maverick1000** [comment]
You are still not getting it, for example your RichTextKeyboardToolbar is a swiftui view, so how would that be using in a UIKit project?  If you still have trouble with what I am asking,  you can call me at 510 333 9920.  

As for documentation it all about swiftui no example in UIKit the only example "RichTextView(data: myData, format: .archivedData)  // Using data".

Below is your swiftui example of  the Editor Screen that has a toolbar, have an issue with how it would be converted back to UIKIt format.

"private extension EditorScreen {

    var editor: some View {
        RichTextEditor(text: $text, context: context) {
            $0.textContentInset = CGSize(width: 10, height: 20)
        }
        .background(Material.regular)
        .cornerRadius(5)
        .focusedValue(\.richTextContext, context)
    }

    var toolbar: some View {
        RichTextKeyboardToolbar(
            context: context,
            leadingButtons: {},
            trailingButtons: {}
        )
    }
}"

If this possible in UIKit, how would. I go about doing it.!!!!!!!!!!!!!!!!!!!!!

**Comment by Maverick1000** [comment]
Are you going to give me answer to my last post!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by danielsaidi** [comment]
Are you trolling me right now? You come across as very aggressive when you spam a dozen exclamation marks, use expressions like that I "don't get it" and demand an answer a few seconds after posting. Not cool.

My advice to you is to first read the [readme](https://github.com/danielsaidi/RichTextKit/blob/main/README.md), then the [getting-started](https://danielsaidi.github.io/RichTextKit/documentation/richtextkit/getting-started) guide, then have a look at the [documentation](https://danielsaidi.github.io/RichTextKit/documentation/richtextkit) and the demo app.

Yes, the `RichTextKeyboardToolbar` is a SwiftUI view, since the main focus of this library is...SwiftUI. As I wrote above, "This is primarily a SwiftUI library". If you want to use it in UIKit, I suggest that you study how to use SwiftUI in UIKit and vice-versa. It's hardly not the responsibility of this library to teach you how to do it.

Good luck.
