### ISSUE TITLE
Editor bugged with an initial value

### ISSUE THREAD

**Issue by dave0111** [danielsaidi/RichTextKit#86]
For some reason, the editor is bugged when the text State variable is initialized to something other than an empty string

In the Demo project's `EditorScreen`, I changed

```
@State
private var text = NSAttributedString.empty
```

to

```
@State
private var text = NSAttributedString(string: "test")
```

After launching the editor, and highlighting the "test" text, selecting a styling button does not apply the relative style to the selected text, unless you first select "underline".
Selecting any style other than "underline" will NOT apply that style to the highlighted text, but if the "underline" style is first selected and deselected right after, every other style can then be applied without problem.

Also, I'm not sure if I'm doing something wrong, but programmatically assigning a new NSAttributedString to the RichTextEditor's text binding, will NOT result in the editor displaying the updated value, that will instead remain unchanged.

I'm on 0.9.1, installed via Swift Package Manager, and the bug was found on:

- MacBook Pro M2 (MacOS 14.1) running both a Designed for iPad app, and the Demo project
- iPad Pro 12.9 (iPadOS 17.1) both with a physical device and with a simulator 
- iPhone 15 Pro Max (iOS 17.1) both physical and simulator

**Comment by danielsaidi** [comment]
Hi @dave0111 

I'm not currently working with this project.

Did you manage to figure something out?

Best

Daniel

**Comment by benlong100** [comment]
Okay, it seems like this is maybe a Sonoma/Xcode 15/iOS 17 problem. First of all, under Sonoma, having the RichTextKit library in my project makes the debugger run incredibly slowly. Second, if I place breakpoints at certain places and step through my code I can sometimes get the RichTextEditor to load with my desired result. At other times it doesn't. So it seems like my code is okay, there's something else going on. Unfortunately, my iPad decided to update itself to iOS 17 so I had to upgrade my Mac. Otherwise, I'd try testing on an earlier Xcode/iOS version.

**Comment by dave0111** [comment]
Unfortunately I could not figure out a solution with a default/initial value, but I found a workaround by just setting my string with `context.setAttributedString(to:)`, on appear.

Also, setting the font size is very glitchy, not sure if I should create a new issue to go more into detail, but could not get that to work either.

**Comment by benlong100** [comment]
Hey Dave,

If you're curious, create a new iOS app project and see if this code works. It works for me. However, trying the same thing in the app I'm trying to build isn't working (by the way, my goal is to hand the rich text editor an HTML file, that's why there's that process of converting HTML to attributable strings):

`
import SwiftUI
import RichTextKit

struct ContentView: View {
   @State  var theEditorText = NSAttributedString("blah blah blah")
   @State var richTextIsVisible = false
   
   var body: some View {
      VStack {
         Button(action: {
            richTextIsVisible = true
         }, label: {
            Text("Make text editor visible")
         })
         if richTextIsVisible {
            EditorView(theText: theEditorText)
         }
      }
      .onAppear(perform: {
         let html = """
         <html>
         <body>
         <h1>Hello, <u>world</u>!</h1>
         </body>
         </html>
         """
         
         let data = Data(html.utf8)

         if let attributedString = try? NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil) {
            theEditorText = attributedString
            print(theEditorText)
         }
      })
      
   }
}

struct EditorView: View {
   @State  var theText : NSAttributedString
   @StateObject var context = RichTextContext()

   var body: some View {
      RichTextEditor(text: $theText, context: context) {_ in
         // You can customize the native text view here
         
      }
      .border(Color(.black), width: 1)
      .padding(.leading, 100)
      .padding(.trailing, 100)
      .padding(.top, 100)
      .padding(.bottom, 100)
   }
}
`

**Comment by benlong100** [comment]
Hey Dave, if you're curious, create a new iOS app project and see if this code works in it. It does for me. My goal is to be able to hand an HTML file to the RichTextEditor, so I've got this bit in here that converts an HTML string into attributed strings. The only way I could paste the code into here was to comment out the HTML bit, so you'll need to uncomment that.

`
//
//  ContentView.swift
//  RichTextPlay
//
//  Created by Happy Wanderer on 11/29/23.
//

import SwiftUI
import RichTextKit

struct ContentView: View {
   @State  var theEditorText = NSAttributedString("blah blah blah")
   @State var richTextIsVisible = false
   
   var body: some View {
      VStack {
         Image(systemName: "globe")
            .imageScale(.large)
            .foregroundStyle(.tint)
         Button(action: {
            richTextIsVisible = true
         }, label: {
            Text("Make it visible")
         })
         if richTextIsVisible {
            EditorView(theText: theEditorText)
         }
      }
      .onAppear(perform: {
       //  let html = """
       //  <html>
//         <body>
//         <h1>Hello, <u>world</u>!</h1>
//         </body>
//         </html>
//         """
         
         let data = Data(html.utf8)

         if let attributedString = try? NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil) {
            theEditorText = attributedString
            print(theEditorText)
         }
      })
      
   }
}

struct EditorView: View {
   @State  var theText : NSAttributedString
   @StateObject var context = RichTextContext()

   var body: some View {
      RichTextEditor(text: $theText, context: context) {_ in
         // You can customize the native text view here
         
      }
      .border(Color(.black), width: 1)
      .padding(.leading, 100)
      .padding(.trailing, 100)
      .padding(.top, 100)
      .padding(.bottom, 100)
   }
}
`

**Comment by benlong100** [comment]
Hey Dave,

Thanks for the update. I tried your setAttrutedString thing but it's not working. This feels like bugs/changes in the latest round of Xcode/MacOS/iOS. I'm toying with the idea of downgrading my iPad and Mac, but there's always the question of whether it's just ultimately a dead-end to go with a library that's no longer being developed.

I have, however got a consistently-working test project. I can't paste it in here, because it's got some embedded HTML that screws up the comment display. If you want to play with it, I could send it to you, though I'm not sure there's any way to PM here.

Ben

**Comment by benlong100** [comment]
Okay, I figured out my problem. It's that NSAttributedStrings are non-mutating. So if you declare one, it's stuck with those contents. So far, I haven't figured out a way to declare it in one place, but fill it with content in another. So the problem is not RichTextKit.

**Comment by dave0111** [comment]
If you declare an NSAttributedString, like you said, it can’t be changed, but you can use NSMutableAttributedString instead, which is mutable.
If I remember correctly, NSMutableAttributedString has an initialiser that takes an NSAttributedString, and you can go back from the mutable to the regular attributed string in the same way

**Comment by danielsaidi** [comment]
@benlong100 @dave0111 

Thank you for providing so much information! While I'm not currently working on this project (freelancer and have been working with clients and commercial projects) it's by no means abandoned. 

Like @dave0111 says - you need an `NSMutableAttributedString` 👍 I will take the library for a test run on the latest macOS and Xcode versions when I have time, but will be happy to merge any fixes you come up with until then.
